version: "3.9"
services:
    app:
        build: ./docker/local/php
        restart: always
        volumes:
            - .:/var/www/html
        links:
            - redis
        ports:
          - "9007:9000"
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        env_file:
            - ".env"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3317:3306"
        volumes:
            - ./docker/local/mysql/data:/var/lib/mysql
    redis:
        image: redis
        ports:
            - "6317:6379"
        restart: unless-stopped
